GET http://localhost:8080/products

###
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Something",
  "description": "Blah",
  "type": "BOOK",
  "price": 100
}

###
GET http://localhost:8080/products/1

###
GET http://localhost:8080/products/100
