### Get all products
GET http://localhost:8080/products

### Add new product
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Something",
  "description": "Blah",
  "type": "BOOK",
  "price": 100
}

### Get existing product
GET http://localhost:8080/products/1

### Get non-existing product
GET http://localhost:8080/products/100

### Create new order
POST http://localhost:8080/orders
Content-Type: application/json

{
  "productsIds" : [1, 2]
}

### Show existing order
GET http://localhost:8080/orders/2

### Show non-existing order
GET http://localhost:8080/orders/100

### Log into application and obtain token
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "chrosciu",
  "password": "Maja"
}

### Get all products using token

GET http://localhost:8080/products
Authorization: Bearer <token>

