incremental:
    generator:
        initial-value: 20
        step: 2
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
    pattern:
        console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd''T''HH:mm:ss.SSSXXX}}){faint}
            %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint}
            %clr([%mdc{requestId:-N/A}]){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan}
            %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
management:
    endpoint:
        shutdown:
            enabled: true
    endpoints:
        web:
            exposure:
                include: '*'
    httpexchanges:
        recording:
            enabled: true
request-logging:
    enabled: true
    include-headers: true
    include-query-string: true
    payload:
        include: true
        max-length: 10000
    urls:
    - /api/*
    - /actuator/*
spring:
    datasource:
        password: admin
        url: jdbc:postgresql://localhost:5432/spring-workshop
        username: admin
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
